version: 2
updates:
  # Actualizar dependencias de npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "â¬†ï¸"
      include: "scope"
    reviewers:
      - "1707505@uab.cat"
    assignees:
      - "1707505@uab.cat"
    labels:
      - "ğŸ”§ maintenance"
      - "dependencies"
    
  # Actualizar GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "â¬†ï¸"
      include: "scope"
    reviewers:
      - "1707505@uab.cat"
    assignees:
      - "1707505@uab.cat"
    labels:
      - "ğŸ”§ maintenance"
      - "github-actions"
